### ISSUE TITLE
conflict with ISMEAR=−5

### ISSUE THREAD

**Issue by lingtikong** [msg-byu/autoGR#27]
Is it possible to write out the list of tetrahedra so that the tetrahedron method with Blöchl corrections can be switched on?

**Comment by glwhart** [comment]
It's not necessarily the case that any GR grid makes an acceptable set of tetrahedra, so this isn't possible in general.

Our tests show that the Blochl method isn't any better on average than standard smearing. We have a paper almost ready to submit on this. If you'll remind me in couple of weeks, I can share the preprint.
