### ISSUE TITLE
Erroneous comma in src/driver.f90, line 33

### ISSUE THREAD

**Issue by haydensoliver** [msg-byu/autoGR#30]
Running `make F90=gfortran kpoints.x` resulted in the following error.

`driver.f90:33:82:
   write(4,'("Dynamic K-point generation: irreducible/reducible: ", I12, "/", I6)'), size(IRKps,1), sum(weights)
                                                                                  1
Warning: Legacy Extension: Comma before i/o item list at (1)`

This compiler error was solved by removing the comma between `write()` and `size()` as below:

`33  write(4,'("Dynamic K-point generation: irreducible/reducible: ", I12, "/", I6)') size(IRKps,1), sum(weights)`

**Comment by braydenbekker** [comment]
This is a warning for a legacy comma in the write statement. I have verified that this is the only write statement with this extra comma. This small change should probably be added to the next pull request.

**Comment by glwhart** [comment]
This has been fixed.
