### ISSUE TITLE
a problem in the file driver.f90

### ISSUE THREAD

**Issue by ferroteam** [msg-byu/autoGR#35]
Hello,
in the driver.f90 there is a line:

call get_inputs(nkpts, lat_vecs, at, B_vecs, offset, find_offset, symm_flag, &
       min_kpts, reps, aeps)
- 10 input parameters.

while in the definition of this subroutine, control_file.f90:

SUBROUTINE get_inputs(nkpts, lattice, atom_type, atom_base, offset, &
       find_offset, symm_flag, min_kpts_flag, eps) 

there are only 9 input parameters.

**Comment by glwhart** [comment]
I'll fix this soon. It was a busy semester and things got put on hold.

**Comment by glwhart** [comment]
Coming back from being dean and teaching again, I've been too busy to keep up with all my github repos. At the end of April, I hope to start addressing all the outstanding issues and PRs

**Comment by glwhart** [comment]
This should all be fixed now with my lastest updates. If you still have problems, please re-open the issue.
